services:
  
  storage:
    build: .
    container_name: storage
    entrypoint: ./start.sh
    restart: always
    volumes:
      - ./:/home/intime/app
    environment:
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET=${R2_BUCKET}
      - R2_ENDPOINT=${R2_ENDPOINT}